### ISSUE TITLE
Error running flekky --source _example build

### ISSUE THREAD

**Issue by richyvk** [xi/flekky#1]
Hi

I installed flekky in a virtual env using virtualenvwrapper. When I run `flekky --source _example build` I get the following error:

```
/Users/macbook/.virtualenvs/flekky/lib/python2.7/site-packages/flekky/flekky.py:245: MissingURLGeneratorWarning: Nothing frozen for endpoints flekky.page_route. Did you forget an URL generator?
  freezer.freeze()
Traceback (most recent call last):
  File "/Users/macbook/.virtualenvs/flekky/bin/flekky", line 11, in <module>
    sys.exit(main())
  File "/Users/macbook/.virtualenvs/flekky/lib/python2.7/site-packages/flekky/flekky.py", line 248, in main
    for filename in os.listdir(source):
OSError: [Errno 2] No such file or directory: '/Users/macbook/Documents/Flask/Flekky-test/_example'
```

Following this I have only an empty `_example _build` folder in the directory I ran `build` in.

Are you able to suggest what I'm doing wrong, or is this a bug?

**Comment by xi** [comment]
Thanks for the report! I think this is an issue in README.rst: It states that you could run the following commands:

```
$ pip install flekky
$ flekky --source _example build
```

However, the `_example` folder is only present in the git repo, so it is not available when installing with pip.

To fix this, added a command `init` to flekky that will bootstrap a new project. I changed README.rst to say

```
$ pip install flekky
$ flekky init
$ flekky build
```

Could you please verify that this works with version 0.3.0?

**Comment by richyvk** [comment]
Hi

I can confirm that running `flekky init` and then `flekky build` successfully builds. Thanks for you help :)

**Comment by xi** [comment]
yeay!
